language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  jobs:
    - LARAVEL=6.0.* TESTBENCH=4.*
    - LARAVEL=7.0.* TESTBENCH=5.*
    - LARAVEL=8.0.* TESTBENCH=6.*
  global:
    - DB_CONNECTION=sqlite
    - DB_DATABASE=":memory:"
    - APP_ENV=testing

matrix:
  fast_finish: true
  exclude:
    - php: 7.2
      env: LARAVEL=8.0.* TESTBENCH=6.*

branches:
  only:
  - master
  - dev
  - /^release-.*$/
  - /^release/.*$/

before_script:
  - composer config discard-changes true
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http/Livewire
before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-update
  - cat composer.json
install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest --no-dev --no-update
script:
  - phpunit --testdox

