anguage: php

env:
  global:
    - DB_CONNECTION=sqlite
    - DB_DATABASE=":memory:"
    - APP_ENV=testing
  matrix:
    - LARAVEL_VERSION=5.5.*
    - LARAVEL_VERSION=5.6.*
    - LARAVEL_VERSION=5.7.*
    - LARAVEL_VERSION=5.8.*

php:
  - 7.2

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer update
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http/Livewire
script:
  - phpunit --testdox

