language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  jobs:
    - LARAVEL=6.0.* TESTBENCH=4.*
    - LARAVEL=7.0.* TESTBENCH=5.*
    - LARAVEL=8.0.* TESTBENCH=6.*
  global:
    - DB_CONNECTION=sqlite
    - DB_DATABASE=":memory:"
    - APP_ENV=testing

matrix:
  fast_finish: true
  exclude:
    - php: 7.2
      env: LARAVEL=8.0.* TESTBENCH=6.*

branches:
  only:
  - master
  - dev
  - /^release-.*$/
  - /^release/.*$/

before_script:
  - composer config discard-changes true
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http/Livewire
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL}" --no-update; fi;
  - if [ "$TESTBENCH" != "" ]; then composer require --dev "orchestra/testbench:${TESTBENCH}" --no-update; fi;
  - composer update

script:
  - phpunit --testdox

